apache/cordova-paramedic

lib/ParamedicConfig.js
lib/appium/AppiumRunner.js
lib/paramedic.js

Run `npm t` showed a list of obvious jshint errors that were simple enough to fix:
```
lib\appium\AppiumRunner.js: line 85, col 14, Unnecessary semicolon.
lib\paramedic.js: line 126, col 13, Confusing use of '!'.
lib\paramedic.js: line 126, col 54, Confusing use of '!'.
lib\paramedic.js: line 332, col 13, Confusing use of '!'.
lib\paramedic.js: line 667, col 2, Missing semicolon.
lib\paramedic.js: line 889, col 68, Missing semicolon.
lib\ParamedicConfig.js: line 140, col 2, Missing semicolon.
lib\ParamedicConfig.js: line 255, col 2, Missing semicolon.
lib\ParamedicConfig.js: line 263, col 2, Missing semicolon.
lib\ParamedicConfig.js: line 310, col 2, Missing semicolon.
lib\ParamedicConfig.js: line 314, col 2, Missing semicolon.
lib\ParamedicConfig.js: line 321, col 2, Missing semicolon. …
```

Fix jshint errors

---

spec/build-fail-plugin/package.json
spec/build-success-plugin/package.json
spec/sh-read-input-plugin/package.json
spec/testable-plugin/package.json
spec/testable-plugin/tests/package.json

This PR adds the most rudimentary package.json possible for plugins and plugin tests.
fixes #31

Add package.json files to plugins and plugin tests

---

README.md
lib/ParamedicTargetChooser.js

With this minor change I could run on a physical device by passing the device id with the --target parameter.

Support Android devices

---

lib/paramedic.js

Android 7.0 tests were failing for `cordova-plugin-inappbrowser`: https://github.com/apache/cordova-plugin-inappbrowser/issues/307 Long research showed that this had to do with the permission buster hanging.
Lo and behold, here we have code for not make a plugin hang on Android 7.
Let's add the inappbrowser plugin to this check and see if this fixes things.
Closes https://github.com/apache/cordova-plugin-inappbrowser/issues/307

Fix inappbrowser on Android 7

---

package.json
spec/build-fail-plugin/package.json
spec/build-success-plugin/package.json
spec/sh-read-input-plugin/package.json
spec/testable-plugin/package.json
spec/testable-plugin/tests/package.json

No need to be able to quickly test wp8 here any more, but being able to test browser (no platform setup at all!) is useful.
(currently includes #34 (so I could actually run this), which will go away after this is merged to master)

Remove npm script for wp8, add for browser

---

main.js

Please review @purplecabbage & @sterlingann.
All.
A bit friendlier error messaging when providing an invalid `--plugin` flag. Fixes [CB-12210](https://issues.apache.org/jira/browse/CB-12210) which was filed by @sterlingann.
Before the change:
```
➔ node cordova-paramedic/main.js --platform android --plugin
cordova-paramedic: creating temp project at /var/folders/sp/5jj48bd57sx78cnldkk5ch_h0000gn/T/tmp-49414mdpFuISIeWQF
/private/var/folders/sp/5jj48bd57sx78cnldkk5ch_h0000gn/T/tmp-49414mdpFuISIeWQF /Users/maj/src
cordova-paramedic: installing plugins
Completed tests at 8:32:32 PM
Collecting logs for the devices.
It looks like there is no target to get logs from.
Uninstalling the app.
TypeError: plugin.indexOf is not a function
at PluginsManager.installSinglePlugin …
```

[CB-12210] require a string when parsing the plugin argument.

---

lib/ParamedicConfig.js
lib/ParamedicTargetChooser.js
lib/appium/AppiumRunner.js
lib/paramedic.js
lib/utils/utilities.js

Extra fix for real device detection on Android.
Includes #24, #25, #43, #44, #45

Various changes

---

.travis.yml

This PR changes the Travis configuration to run paramedic with more platforms locally (added `browser`) and run on SauceLabs at all (`browser`, `ios` and `android`).
Follow up to even further improve is tracked in #82
closes #36

[CI] Update Travis config: More local, Saucelabs

---

lib/ParamedicKill.js

Android
Kills 64bit emulator on Mojave
OSX Mojave, Emulator 28.0.16,  system-images;android-28;google_apis;x86

Updated ParamedicKill.js to support qemu-system-x86_64

---

package.json

iOS
Fixes the test command in `package.json`
Successfull run of `npm test` locally

add build flag to iOS test command

---

debug-mode-plugin/scripts/disable-debug-mode.js
debug-mode-plugin/scripts/enable-debug-mode.js

none
Fixes: #108
Replaced `requireCordovaModule` with `require`

Replace requireCordovaModule with require

---

.travis.yml

`.travis.yml` was very repetitive for the Android parts. @timbru31 suggested looking into "YAML Anchors", which I did and applied in this PR (via https://medium.com/@tommyvn/travis-yml-dry-with-anchors-8b6a3ac1b027).

Improve Android parts of .travis.yml (use anchor/alias)

---

README.md

`--target` can (and is) also used for iOS, not only Android as documented.

Document usage of --target for iOS

---

.travis.yml

This rewrite the travis CI config in a way so that it can almost just be copied over to the plugin repos (besides the Sauce Key in `addons.jwt.secure`). This should make updating the config in the plugins much easier and more efficient.
- Extract `PARAMEDIC_BUILDNAME` to `before_script` to make it more obvious this is a variable
- run `npm run eslint` (and fix file that was not passing that check)
- run `npm install -g github:apache/cordova-paramedic` if not running in paramedic repo
- Create `TEST_COMMAND`, `PARAMEDIC_PLUGIN_TO_TEST` and `PARAMEDIC_COMMAND` that are filled depending on what repo the config is run for (paramedic vs. plugin)
- simplify syntax
---
@alsorokin This changes the format of the buildname on Saucelabs from `travis-plugin-splashscreen-383.8` to …

Make Travis CI more copy-able to plugins

---

.travis.yml
conf/pr/ios-10.0.config.json
conf/pr/ios-9.3.config.json

https://wiki.saucelabs.com/display/DOCS/2019/03/07/Announcing+End+of+Life+for+old+OS+versions+on+Sauce+emulators+and+simulators

Remove unsupported SauceLabs iOS simulators (iOS 9.3 and 10)

---

.travis.yml
spec/testable-plugin/tests/foo/package.json

Before, some plugins had something like this:
```
- env: TEST_DIR=.
language: objective-c
- env: TEST_DIR=./tests/ios
language: objective-c
```
which was run via
```
- if [[ "$TEST_DIR" != "" ]]; then
cd $TEST_DIR;
npm install;
npm test;
else
cordova-paramedic --config pr/$PLATFORM --plugin . --shouldUseSauce --buildName travis-plugin-camera-$TRAVIS_JOB_NUMBER;
fi
```
the `if [[ "$TEST_DIR" != "" ]]; then` was not part of the paramedic config, so got overlooked when cleaning up the travis.yml that then got copied over to plugins. When adding the `env` back to the plugin travis.yml config, it failed (see #141).
---
As this is an important feature for 2 plugins, it has to be reinstated:
- `TEST_DIR=.` only ran the local `npm test`, this is now part of travis.yml anyway.
- …

ADDITIONAL_TESTS_DIR (to replace TEST_DIR)

---

lib/paramedic.js

This PR is basically same as the previous PR:  https://github.com/apache/cordova-paramedic/pull/51#issuecomment-487122818
This PR is based on the current master branch.
All platforms (tests only)
Main target is Windows 10.
Fix #38 .
Without this PR, in runLocalTests following tasks are called in order.
1.   launching test application
2.  waiting application test results
However sometimes jasmine's tests in application are finished before the corodva-paramedic starts to wait the test results. I met this issue in Windows 10. (Please see #38)
With this PR, the above two tasks are called in parallel.
Then the cordova-paramedic can detect jasmine tests' results normally.
In my local PC (Windows 10),
```
npm run test-windows
```
(with Windows Loopback Exemption Manager as mentioned …

execute launching app and waiting results in parallel

---

.travis.yml
conf/pr/android-9.0.config.json

https://wiki.saucelabs.com/display/DOCS/2019/05/30/Android+9.0%2C+now+available+on+Sauce+Labs+emulators

CI, Saucelabs: Android 9 Emulator

---

lib/appium/AppiumRunner.js
lib/appium/helpers/wdHelper.js
spec/testable-plugin/appium-tests/common/common.spec.js
spec/testable-plugin/plugin.xml

This adds Appium tests to the `testable-plugin` which is used to test Paramedic functionality.
The spec file is extracted from https://github.com/apache/cordova-plugin-contacts/blob/master/appium-tests/common/common.spec.js and probably pretty bad.
CI is of course failing because of https://github.com/apache/cordova-paramedic/issues/142

feat: Appium "Test"

---

.travis.yml
package.json

Let's push node to what is currently possible, then roll that out to all plugins (node on CI is only used for testing, thus is not a breaking change for the plugins). This should us give a few months or years until we have to do that again, but can really use all the modern stuff.
Note that this PR only changes the node version used on CI, and doesn't change the code at all - that will happen with further PRs. But as this is the start of major breaking changes, I decided to +1 the major version here as well.

ci: node 12

---

.travis.yml
conf/pr/android-4.4.config.json
conf/pr/android-5.1.config.json
conf/pr/android-6.0.config.json
conf/pr/android-7.0.config.json
conf/pr/android-7.1.config.json
conf/pr/android-8.0.config.json
conf/pr/android-8.1.config.json
conf/pr/android-9.0.config.json
conf/pr/local/android-4.4.config.json
conf/pr/local/android-5.1.config.json

IMO when the plugins are tested it might be best to test against the latest release even if the CLI/Lib pinning has not been updated.
This PR updates the cordova-android platform to use `@latest` to ensure that npm installs the latest release and not the pinned version from `cordova-lib`.
Additionally, to be inline with the current `android@latest` platform, the development environment & tools were updated.

breaking: use latest android platform & development tools 

---

.travis.yml
conf/pr/browser-chrome.config.json
conf/pr/browser-edge.config.json
conf/pr/browser-firefox.config.json
conf/pr/browser-safari.config.json
conf/pr/ios-11.3.config.json
conf/pr/ios-12.0.config.json
conf/pr/ios-12.2.config.json
conf/pr/local/browser.config.json
conf/pr/local/ios-10.0.config.json
conf/pr/local/ios-9.3.config.json
conf/pr/local/windows-10-store.config.json
conf/pr/windows-10-store.config.json
sample-config/.paramedic.config.js

IMO when the plugins are tested it might be best to test against the latest release even if the CLI/Lib pinning has not been updated.
This PR updates the platform to use `@latest` to ensure that npm installs the latest release and not the pinned version from `cordova-lib`.
Additionally, to be inline with the current `@latest` platforms, the development environment & tools were updated.

breaking: use latest platform & development tools

---

.travis.yml
conf/pr/android-10.0.config.json

Android
Adds android 10 device as a potential config option.
Ran `npm test`, however failing locally, claiming that my android emulator is out of date, when I have the latest available android emulator installed. Want to see if test runs successfully on travis.

feat: android 10 configs

---

lib/ParamedicApp.js

This is to get tests passing for iOS temporarily while we work on the release for `cordova-plugin-test-framework`
There could be other future changes to `cordova-plugin-test-framework` while working on the rest of the issues. Would be nice to not hinder plugin testing if possible while trying to resolve the remaining issues.
This change will be reverted back to an official release after all issues are resolved and the framework release is complete.

tmp: use cordova-plugin-test-framework master repo

---

lib/ParamedicSauceLabs.js

this is always true with cordova-ios >=6.  
Travis should pass the iOS specs again.

fix(ios): remove WKWebView check

---

.github/workflows/android.yml
.github/workflows/chrome.yml
.github/workflows/ios.yml
conf/pr/local/android-11.config.json
conf/pr/local/android-5.1.config.json
conf/pr/local/ios-11.4.config.json
lib/ParamedicApp.js
lib/ParamedicTargetChooser.js
lib/appium/AppiumRunner.js
lib/appium/helpers/wdHelper.js
lib/paramedic.js
lib/utils/utilities.js
paramedic-plugin/package.json
paramedic-plugin/plugin.xml

Migrate paramedic to GH Actions
- Appium tests are not passing but everything else is running OK. No core plugins uses Appium test for android.
- Chrome: https://github.com/erisu/cordova-paramedic/actions/runs/1175218752
- Android: https://github.com/erisu/cordova-paramedic/actions/runs/1175218751
- iOS: https://github.com/erisu/cordova-paramedic/actions/runs/1175218750

ci: add gh-actions workflow

---

package.json

Bump node engine requirement to the maintained-LTS version.
* `>=12`

feat!: bump node engine requirement >=12

---

paramedic-plugin/plugin.xml

Android
Make tests green.
Set on AndroidManifest:
```
<application
android:requestLegacyExternalStorage="true"
android:usesCleartextTraffic="true" />
```
- GitHub Actions Test Results.

test(paramedic-plugin): update edit-config for various plugin support

---

.github/workflows/ios.yml

none
> The macOS 10.15 Actions runner image [started our deprecation process](http://app.github.media/e/er?s=88570519&lid=3339&elqTrackId=f7a2ee0f7fb04d009f301a8990fdc3a7&elq=e5f8577314b546cebad4e5512f96dc02&elqaid=2633&elqat=1) on 5/31/22 and will be fully unsupported by 8/30/22.
Remove macOS 10.15 from the workflow.
This also removes iOS 12 from the testing matrix.
See Action Results

ci(ios): drop macos 10.15 & iOS 12

---

.github/workflows/ios.yml

N/A
Add the `continue-on-error` flag to allow all tests to run even if one fails.
Sometimes failures are caused by a timeout. Timeouts should not terminate all tests.  
Also matches with Android config.
Set `continue-on-error` to `true`.

ci(ios): add continue-on-error flag

---

lib/ParamedicApp.js

Various Android tests are failing because of the config munging order.
This PR changes the order of the project setup and the plugin install as a temporary workaround for Android plugin testing.
This change does not resolve the underlining issue.
**Current Order of Paramedic for Reference:**
* Install Plugins
* Install Plugins
* Install Test For Existing Plugins
* Install CI Testing Framework Related Plugins
* Setup Project Config For Test Framework
* Install Platform
Some plugins and the test plugins will inject elements into the `AndroidManifest` with `config-file`. For example, let us say the `provider` node is injected into the path of `/manifest/application`.
Next, the CI testing plugin attempts to update the `/manifest/application` node by appending attributes with `edit-config`. …

fix(android): change order of project setup & plugin install

---

.github/workflows/android.yml
conf/pr/local/android-13.config.json

n/a
Update Testing for Android
- Drop minimum 5.1 testing
- Increased minimum 7.0 testing
- Removed SDK 31 testing (Covered by SDK 32)
- Added SDK 33 testing
- Updated Emulator action
n/a (See Action Resuls)

ci(action): update android workflow

---

conf/pr/local/ios-13.x.config.json
conf/pr/local/ios-14.x.config.json
conf/pr/local/ios-15.x.config.json
lib/utils/utilities.js

Cordova CLI 12.x requires platform name to be included with `cordova run --list` command
Added `ios` to the fetching of iOS run list.
See GitHub Actions

fix: cli 12 requires platform name w/ cordova run --list

---

conf/pr/local/ios-13.x.config.json
conf/pr/local/ios-14.x.config.json
conf/pr/local/ios-15.x.config.json
conf/pr/local/ios-16.x.config.json

the `^` in the target names is making paramedic not find the devices when running the tests because the simulator names start with `\tiPhone`, not with `iPhone`

fix: correct name of iOS targets

---

lib/PluginsManager.js

since macOS monterrey, port 5000 is taken by control center, use 5001 instead
I don't think it affects the CI, but it's needed for local run of paramedic

fix: Update file-transfer port

---

paramedic-plugin/plugin.xml

n/a
Updated paramedic plugin to allow list 127.0.0.1 for all platforms and also included 10.0.2.2.
n/a

chore: update paramedic-plugin allow list for file-transfer's server

---

lib/utils/utilities.js

simulator lists has a tab `\t`, so the `^` start of string regex was failing to find anything.
fixes #264

fix: Finding first ios simulator

---

.github/workflows/android.yml

n/a
Use JDK 17 which is minimum requirement for latest `cordova-android` release
bump default java version to 1
tested with file plugin

ci(android): set default java version to 17

---

.github/workflows/android.yml

Android
Following below comment:
https://github.com/apache/cordova-plugin-geolocation/pull/291#issuecomment-2827376314
> The Apache Software Foundation is moving toward blocking tags like v1 and prefers commit hash IDs instead.
I agree because we can avoid unexpected change such as caused by third-party tool makes breaking-change without update major version or remakes tags.
- Change `ReactiveCircus/android-emulator-runner@v2` to `v2.34.0`'s [commit id](https://github.com/ReactiveCircus/android-emulator-runner/releases/tag/v2.34.0)
- The other tools are GitHub’s core actions or already using commit id
Android Testsuite successed.

ci: use commit id
