- lib/ParamedicConfig.js
- lib/paramedic.js
- lib/utils/execWrapper.js
- lib/utils/index.js
- lib/utils/utilities.js
- main.js
- package.json
https://issues.apache.org/jira/browse/CB-11332
> CB-11332 Added Saucelabs support

- lib/appium/AppiumRunner.js
https://issues.apache.org/jira/browse/CB-11568
> CB-11568 Run Appium tests from any directory

- README.md
https://issues.apache.org/jira/browse/CB-11575
> CB-11575 Added a notice about loopback exemption to the readme file

- lib/ParamedicConfig.js
- lib/paramedic.js
- main.js
https://issues.apache.org/jira/browse/CB-11684
> CB-11684 Introduced --skipAppiumTests and --skipMainTests args

- README.md
- lib/LocalServer.js
- lib/ParamedicKill.js
- lib/PluginsManager.js
- lib/paramedic.js
- paramedic-plugin/paramedic.js
https://issues.apache.org/jira/browse/CB-11926
> CB-11926 Pass the file transfer server address to the tests via variable

- package.json
> AppVeyor: Test browser instead of Windows

- .gitignore
- lib/LocalServer.js
- lib/ParamedicAppUninstall.js
- lib/ParamedicKill.js
- lib/ParamedicLog.js
- lib/ParamedicTargetChooser.js
- lib/ParamediciOSPermissions.js
- lib/PluginsManager.js
- lib/appium/AppiumRunner.js
- lib/paramedic.js
- lib/utils/execWrapper.js
- lib/utils/utilities.js
- package-lock.json
- package.json
- Mark as `0.6.0-dev`, update author, fix licence
- All executed commands are output (to make it easier to follow what is going on or debug problems)
- Some additional comments 
- Some additional console output
- Multiple tiny fixes to output
> Improve code and traceability

- lib/ParamedicAppUninstall.js
- lib/ParamedicKill.js
- lib/ParamedicLog.js
- lib/ParamedicTargetChooser.js
- lib/PluginsManager.js
- lib/paramedic.js
- lib/utils/utilities.js
- main.js
https://github.com/apache/cordova-paramedic/pull/78 broke some of the changed commands by not removing the options array. It is not needed by `exec` as the chosen values are set in there.
> Fix exec usage

- .travis.yml
This adds Safari, Firefox and Edge to the CI configuration to be tested on Saucelabs.
> Improve SauceLabs Browser setup

- .travis.yml
- lib/appium/helpers/wdHelper.js
- package-lock.json
- package.json
> fix: workaround recursive object error

- .travis.yml
- conf/pr/ios-12.2.config.json
> [CI] Test iOS 12.2 on SauceLabs

- .travis.yml
- lib/ParamedicLogCollector.js
- lib/ParamedicTargetChooser.js
- lib/paramedic.js
- lib/utils/utilities.js
- package.json
None
Local Test to Pass
- Quotation Wrap Target
- Expand iOS Test Images
- Cleanup `getSimulatorModelId`
- `npm run test-ios`
- Travis CI
> Improve Local Testing

- .travis.yml
> Remove Android 4.4 that is not available on SauceLabs any more

- lib/appium/AppiumRunner.js
> Fix AppiumRunner getPackagePath bug

- lib/paramedic.js
- lib/utils/utilities.js
- package-lock.json
- package.json
none
fixes: https://github.com/apache/cordova-paramedic/issues/158
Improve the way targets is fetched for iOS
Added and used `execa` to fetch all targets and used JS to filter, pick, and trim the targeted target.
- manually tested the code outside of paramedic.
> refactor: fetch target (simulator) with execa

- lib/LocalServer.js
- lib/ParamedicApp.js
- lib/ParamedicConfig.js
- lib/ParamedicSauceLabs.js
- lib/paramedic.js
Additional output during the run to better structure it and make it easier to understand what is going on.
> feat: Additional logging to better structure generated output

- .travis.yml
- appveyor.yml
Ref https://github.com/apache/cordova/issues/79
> ci: updates Node.js versions

- .travis.yml
> ci(travis): removes obsolete key and adds license header

- README.md
* Add GitHub Status Badge
* Merge in after #217
> ci(gh-actions): add status badge

- README.md
* Updates README
* Merge in after #218
> doc: update & format readme

- .eslintrc.yml
- .github/workflows/lint.yml
- .github/workflows/node.yml
- lib/LocalServer.js
- lib/ParamedicApp.js
- lib/ParamedicSauceLabs.js
- lib/ParamedicTargetChooser.js
- lib/Reporters.js
- lib/appium/AppiumRunner.js
- lib/appium/helpers/wdHelper.js
- lib/paramedic.js
- lib/utils/utilities.js
- package-lock.json
- package.json
* Use Cordova's ESLint package
* Applied both manual and automatic changes.
* Added GitHub Actions Workflow to run liniting
> feat!: upgrade eslint process w/ workflow testing

- .github/workflows/android.yml
- .github/workflows/chrome.yml
- .github/workflows/ios.yml
Platform tests do not need to run when modifiying:
- Markdown files `**.md`
- `LICENSE` file
- ESLint configurations `.eslint*`
- CI
> ci: add ignore cases to run platform test

- .github/workflows/android.yml
- conf/pr/local/android-12.config.json
- conf/pr/local/android-12L.config.json
none
* Speed up Android Testing
* Use latest action dependencies
* Update JAVA requirements
* Add Android 12 & 12L
* Test only the last 3-4 and lowest minimum APIs
* Set default JAVA version to 11
* Update the JAVA distro to temurin
* Update Actions
* Created Android 12 & 12L Configs & Added to Workflow
See GH Action Results
> ci(android): refactor workflow

- lib/ParamedicSauceLabs.js
- lib/appium/AppiumRunner.js
ios
Fix output path for Cordova-iOS 7
n/a
> fix(ios): build output path for cordova-ios@7.0.0
